name: 01 - OIDC Test
on: { workflow_dispatch: {} }
permissions: { id-token: write, contents: read }
jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          allowed-account-ids: ${{ vars.AWS_ACCOUNT_ID }}
      - run: aws sts get-caller-identity
