name: 02 - PR CI DevSecOps
on:
  pull_request:
    branches: [main]
permissions: { id-token: write, contents: read }
env:
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0 }
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform fmt -check -recursive
      - uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          allowed-account-ids: ${{ vars.AWS_ACCOUNT_ID }}
      - run: |
          terraform -chdir=terraform init             -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"             -backend-config="key=aos-warranty/dev/terraform.tfstate"             -backend-config="region=${{ vars.AWS_REGION }}"             -backend-config="encrypt=true"             -backend-config="use_lockfile=true"
      - run: terraform -chdir=terraform validate
      - uses: terraform-linters/setup-tflint@v6
        with: { tflint_version: v0.64.0 }
      - run: cd terraform && tflint --init && tflint -f compact
      - run: pip install checkov bandit
      - run: checkov -d terraform --compact
      - run: bandit -r glue aiops
      - uses: aquasecurity/trivy-action@v0.36.0
        with: { scan-type: config, scan-ref: terraform, severity: 'HIGH,CRITICAL', exit-code: '1' }
      - uses: gitleaks/gitleaks-action@v3
        env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      - run: terraform -chdir=terraform plan -no-color
